[package]
name = "oxide-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
oxide-model.workspace = true
oxide-engine-clash.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
libc.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream", "socks"] }
fs2 = "0.4"
[dev-dependencies]
tempfile = "3"

